### ISSUE TITLE
Define rate limitation / quota by application (override the default "global" configuration)

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/release#1]

**Comment by NicolasGeraud** [comment]
What is the use case of more than 1 api-key for an application ?

I think this feature must not be associated with ratelimit policy. This means that we should found a solution which works for all policies.

**Comment by brasseld** [comment]
@NicolasGeraud you can have more than 1 api key for an application / API if you ask the system to generate a fresh api key. By doing so, previous api keys is still valid but with an expiration date settled (+ 1 hour). During this time, consumers can use both api keys to consume the API.

**Comment by NicolasGeraud** [comment]
I'm agree with that, but why would we want configure a quota by apikey like the original title of this issue suggested it ?

**Comment by brasseld** [comment]
It was a mistake. Rate limitat is defined by application, not apikey.

**Comment by NicolasGeraud** [comment]
ok, i've renamed gravitee-policy-ratelimit/issues/1

**Comment by brasseld** [comment]
gravitee-policy-ratelimit/issues/1
