### ISSUE TITLE
Simulate a release Workflow

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/release#126]
# Description

Simulate a _release_ and _dry run_ workflow with CircleCI.

## Dev repos
Implements 3 workflows on a dev repo (just echo) : 
 - build
 - dry run
 - release

Only run an `echo` command on each workflow.

## Release repo

Implements 2 workflows on the release repo:
 - dry run
 - release

The `dry run` workflow scan the `release.json` file and launch a `dry run` workflow on each snapshots.
The `release` workflow scan the `release.json` file and launch a `release` workflow on each snapshots.

# Validation

* [x] on a dev repo, 1 PR triggers a workflow build
* [x] on a dev repo, 1 commit on a PR branch tiggers a workflow build

* [x] on the release repo, 1 PR triggers nothing
* [x] on the release repo, 1 commit on a PR branch tiggers nothing
* [x] on the release repo, 1 commit on a classic branch (master or 1.2.x) triggers a dry run
* [x] on the release repo, via cURL we
* [ ] on a dev repo, 1 commit on a classic branch (master or 1.2.x) triggers a workflow build 

🚨 **CircleCI cannot start a pipeline on a PR AND on a commit with a filter branch**

**Comment by Jean-Baptiste-Lasselle** [comment]
```markdown
* [ ] has to be a bullet, in 
* [ ] addition to a checkbox 
* [x] this one is checked
```

* [ ] has to be a bullet, in 
* [ ] addition to a checkbox 
* [x] this one is checked

**Comment by Jean-Baptiste-Lasselle** [comment]
I think `build` workflow is meant for the _**product release dry-run**_ , and if so, a simple Circle CI Pipeline job will be enough : 

* `product release` execute the `build` job, then the mvn plugin execution which modifies pom.xml to strip out `-SNAPSHOT` and finally the mvn deploy to the maven central repository
* while `product release dry run`  Pipeline Workflow would only execute the `build` job (iwould add a few more thigns, liek echoing all product release shell commands, to check parameters values, to check what would have happened when executing the product release"not in dry-run mode".

Then `build` job workflow would have nothing to do with Pull Requests : The Pull Request Bot will detect if source branch of pull request is starting : 
* with `support-` prefix, and then trigger the `support_pr_review` workflow
* or with `issue-` prefix, and then trigger the `dev_pr_review` workflow

Also then easily possible : 
* in case prefix is `snyk-`, then trigger a new workflow named `secops_pr_review`
* in case prefix is `dependabot-`, then trigger a new workflow named `auto_dep_updates_pr_review` 
* etc...

Finally, when prefix is unexpected, then the pul request bot, will throw an error, and add a comment in the pull request , using the Github API v4 : "Hey, yoour pull request source branch does not follow CICD naming conventions: (then add help with list of all prefix coventions, and their purpose, did you mean to trigger a support or dev pull request?) closing pull request, rejected, create again yur work branch following CI cd naming conventions"

**Comment by Jean-Baptiste-Lasselle** [comment]
to test last mentioned commit, still need to : 
* fork all gravitee IO components git repo to `gravitee-lab` test github organization
* add `circleci/config.yml` on every _"release"_ ("classic") branch of all of those git repos,  with the exact following definition : cc

* And here is the new GNU Menu of the Gravitee CI CD Orchestrator : 

```bash
jbl@poste-devops-jbl-16gbram:~/gravitee-orchestra$ npm start -- --help

> GraviteeReleaseOrchestrator@0.0.2 start /home/jbl/gravitee-orchestra
> node ./dist/index.js "--help"


+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x
I am the Gravitee CI CD Orchestrator !
+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x

Options:
      --help        Show help                                          [boolean]
      --version     Show version number                                [boolean]
  -d, --dry-run

                      Use this option to run the CICD Process Stage in 'dry run'
                      mode.                            [boolean] [default: true]
  -s, --cicd-stage  Use this option to specify the CICD Process to run.

                    ['mvn_release'] In the
                    [https://github.com/gravitee-lab/release] gravitee-lab git
                    repo, will run the maven release process, handling all
                    dependency tree parallelization, with reactive behavior
                    (using RxJS), based on the 'release.json' versioned in the
                    https://github.com/gravitee-lab/release git repository

                    ['pull_req'] In every the gravitee-lab product component
                    git repo (dev git repo), will run the docker release
                    process : docker builds and push all docker images for the
                    product, LTS and STS Releases

                    ['docker_release'] In the [https://github.com/gravitee-lab
                    /docker-library] gravitee-lab git repo, will run the
                    docker release process : docker builds and push all docker
                    images for the product, LTS and STS Releases

                    ['rpm_release'] In the
                    [https://github.com/gravitee-lab/rpm-library] gravitee-lab
                    git repo, will run the RPM release process : builds RPM
                    packagesand publishes them to https://packagecloud.io/

                    ['doc_release'] builds and publish the Gravitee
                    Documentation to https://docs.gravitee.io

                    ['deploy_demos'] bluegreen deploys all public gravitee
                    demos

                    ['social'] builds and publish the Social networks , and
                    communication channels announcements (twitter, medium.com,
                    hackernews, facebook, linkedIn, Jumbo posts on website)

            [required] [choices: "mvn_release", "docker_release", "rpm_release",
              "doc_release", "deploy_demos", "social_announcements", "pull_req"]
jbl@poste-devops-jbl-16gbram:~/gravitee-orchestra$ npm start -- --version

> GraviteeReleaseOrchestrator@0.0.2 start /home/jbl/gravitee-orchestra
> node ./dist/index.js "--version"


+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x
I am the Gravitee CI CD Orchestrator !
+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x+x

0.0.2
jbl@poste-devops-jbl-16gbram:~/gravitee-orchestra$ git tag -ln
0.0.1           Basic Source Code is ready, tooling is there, build cycle defined, still lacks TDD testing stack
DEMO_AZIZE      feat(specs_implementation): added [Monitor.ts] module, and in this version [npm run dev showcases a retry session] based on a well known REST API Endpoint
DOCKERIZED_YOU  Howdy, now the Circle CI Pipeline for the Gravitee CI CD Orchestrator does build and push the docker image. Got ya
DOCKER_BUILD_OK First Docker build proces as multistage build works fine in Circle CI Pipeline.
REACTIVE_TEST1  This test proves you need a new RxJS Subject for each Parallel Execution Set, see line 226 in [src/modules/circleci/CircleCiOrchestrator.ts]
REACTIVE_TEST2  Huuuuuge : Now one parallel execution set starts triggering pipelines if and only if previous one has received Circle CI Responses for all pipeline triggers. Huge honestly.
REACTIVE_TEST3  feat(specs_implementation): fiuxe my little array index bug, now all parallel execution sets do complete triggering pipelines, not any is missing, and the final Error, is on purpose, se the throw new Error("Stop DEbug point")
REVERSE_ENG     see [documentation/jfrog/README.md]: reversed engineered groovy scirpt [back to bash]
jbl@poste-devops-jbl-16gbram:~/gravitee-orchestra$ # npm start -- -s mvn_release --dry-run
jbl@poste-devops-jbl-16gbram:~/gravitee-orchestra$ 
jbl@poste-devops-jbl-16gbram:~/gravitee-orchestra$ cat package.json |grep version
  "version": "0.0.2",
    "oci": "docker version && docker ps -a && docker images"
jbl@poste-devops-jbl-16gbram:~/gravitee-orchestra$ 
```

**Comment by Jean-Baptiste-Lasselle** [comment]
* trigger Product Release in "non-dry-run" mode, using a cURL Circle Ci API v2 invocation : 

```bash
export CCI_API_TOKEN='xxxxxxxxxxxxxxxxxxxxx'
brew install jq
# Choose the workflow
export GIO_CICD_ACTION="wet_release"

# Choose the branch
export GIT_BRANCH="master"
export GIT_BRANCH="develop"

export GIT_BRANCH="1.20.x"
export GIT_BRANCH="1.25.x"
export GIT_BRANCH="3.0.0-beta"
export GIT_BRANCH="3.0.x"
export GIT_BRANCH="3.1.x"
export GIT_BRANCH="3.0.x"

export PIPE_PARAMS="{ \"parameters\": { \"gio_action\": \"${GIO_CICD_ACTION}\",  }, \"branch\": \"${GIT_BRANCH}\" }"

curl -d "${PIPE_PARAMS}" -X POST https://circleci.com/api/v2/project/gh/gravitee-lab/release/pipeline -H 'Accept: application/json' -H 'Content-Type: application/json' -H "Circle-Token: ${CCI_API_TOKEN}" | jq .

```

**Comment by Jean-Baptiste-Lasselle** [comment]
note : 
* some irregularities happen in the release.json files, which generates execution errors of the Gravitee CI CD Orchestrator ,: 
  *  for example, there are components for which no version prpperty is declared at all 
  * see https://github.com/gravitee-lab/release/blob/ea104cb8960a0cd872ac2eaa5fa24e451b302090/release.json#L30

**Comment by Jean-Baptiste-Lasselle** [comment]
basically : most of what's left todo on this review, is setting up and running tests : 
* forking many repos and adding `.circleci/config.yml` on all releases ("classic") branches
* exactly like this one : https://github.com/gravitee-lab/GraviteeCiCdOrchestrator/issues/25#issue-705818394

**Comment by Jean-Baptiste-Lasselle** [comment]
# Review

* The following requirements Involve the "dev repos" (Gravitee components repo, or Gravitee `git` repo versioning GRavitee source code, to be clear)  
  * [ ] on a dev repo, 1 PR triggers a workflow named `build`
  * [ ] on a dev repo, 1 commit on a PR branch triggers a workflow named `build`
  * [ ] on a dev repo, 1 commit on a classic branch (`master` or `1.2.x`) triggers a workflow `build`= > there something to discuss, if Circle CI is configured to build Pull Request, it will "only build pull requests" . Then, a commit on a classic branch (for example git branch `1.2.x`) can trigger a workflow if and only if there is an opened Pull Request, with source branch this same "classic" branch, in this example branch `1.2.x`. 

* The following requirements involve the release repo :  
  * [ ] On the release repo, 1 PR triggers nothing
  * [ ] On the release repo, 1 commit on a PR branch triggers nothing
  * [ ] On the release repo, 1 commit on a classic branch (`master` or `1.2.x` etc...) triggers a dry run
  * [ ] On the release repo, via `cURL` we can trigger release (non-dry) on any "classic" branch (`master`, `1.20.x`, `1.25.x`, `1.30.x`, `3.0.x-beta`)


* [ ] The following requirements Involving the "dev repos" require forking all those repo to the `gravitee-lab` github.com Organization 
* [ ] Testing the `--dry-run` GNU Option requires fixing issue https://github.com/gravitee-lab/GraviteeCiCdOrchestrator/issues/26

**Comment by Jean-Baptiste-Lasselle** [comment]
note that CICD Orchestrator [could identify one problem in the `release.json` on `3.0.0-beta`](https://app.circleci.com/pipelines/github/gravitee-lab/release/55/workflows/0ce1890e-4f52-48fa-8cbd-99b20cff159e/jobs/62) : 
* a component named `gravitee-policy-xsd` is declared
*but it is notpresent anywhere in the `buildDependencies` section
* causing Parallel execution orchestration impossible on branch `3.0.0-beta`

**Comment by Jean-Baptiste-Lasselle** [comment]
## Review of the dry run

#### Execution Flow for the dry run and non dry run release

* using curl, launching a dry-run release : 

```bash 
export CCI_TOKEN="secretvalue"
export ORG_NAME=gravitee-lab
export REPO_NAME=release

export PAYLOAD="{ 
  \"parameters\": {
         \"gio_action\": \"dry_release\"
       },
       \"branch\": \"3.0.x\"
}"

curl -X POST -d "${PAYLOAD}" https://circleci.com/api/v2/project/gh/${ORG_NAME}/${REPO_NAME}/pipeline -H 'Content-Type: application/json' -H 'Accept: application/json' -H "Circle-Token:  ${CCI_TOKEN}"

```


#### Task detail

* For the Gravitee CI CD Orchestrator : 
  * when gnu options are `-s mvn_release --dry-run true`, the relase dry run is launched,
  * when gnu options are [-s mvn_release --dry-run false], then the non-dry maven release is launched
* For the https://github.com/gravitee-lab/release git repo : 
  * 

#### Test Scenario
