### ISSUE TITLE
Perform an APIM dry run without dependencies

### ISSUE THREAD

**Issue by NicolasGeraud** [gravitee-io/release#128]
# Description

Perform a `dry run` release of APIM for components without SNAPSHOT dependencies. 
We have to implement the real `dry run` on all repos. 

# Validation

* [ ] on the release repo, manually start a dry run, all SNAPSHOTS repo will run a dry run job with the real maven dry run

see https://github.com/gravitee-io/jenkins-scripts/blob/3919a90fe32b04782e11d3695de1d3ed3c8da165/src/main/groovy/releasemaven.groovy#L39-L58

### Tasks details

TODO complete

**Comment by Jean-Baptiste-Lasselle** [comment]
For this task, I have Same question than https://github.com/gravitee-io/release/issues/129#issuecomment-699488783

**Comment by Jean-Baptiste-Lasselle** [comment]
ok, so basically at this stage, we need #132 completed, and then : 
* add maven command into dry run workflows of each dev repo

```bash
# 1.3.1-SNAPSHOT -> to 1.3.1
mvn -B versions:set -DnewVersion=1.3.1 -DgenerateBackupPoms=false

# detection si c'est une version de maintenance (un patch, ou une nouvelle feature/un breaking change) : 
# les versions qui terminent par '.0' ne sont pas de maintenance sinon c'est une version de maintenance


# donc l'enjeu ci dessous est que si c'est une version de maintenance ou pas, on pourra 
# vouloir une politique différente : 
# soit on autorise l'upgrade automatique des versions majeures mineures
# soit on ne l'autorise pas : notre politique n'est pas complètement fixe de ce côté
# il y a des cas où l'on souhaite l'update automatique

                    if (c.version.isMaintenance()) { # keep detection of is maintainance or not : maybe we want different 
                        mvn -B -U versions:update-properties -Dincludes=io.gravitee.*:* -DallowMajorUpdates=false -DallowMinorUpdates=false -DallowIncrementalUpdates=true -DgenerateBackupPoms=false
                    } else {
                        mvn -B -U versions:update-properties -Dincludes=io.gravitee.*:* -DallowMajorUpdates=false -DallowMinorUpdates=false -DallowIncrementalUpdates=true -DgenerateBackupPoms=false
                    }

# enfin, on veux faire le mvn clean install en insérant le git commit id pour le BUILD NUMBER

                    withEnv(["GIT_COMMIT=${git_commit}"]) {
                        // deploy
                        if (dryRun) {
                            sh "mvn -B -U clean install"
                            sh "mvn enforcer:enforce"
                        } else {
                            sh "mvn -B -U -P gravitee-release clean deploy"
                        }



```

**Comment by Jean-Baptiste-Lasselle** [comment]
pour cette étape on ne fait pas de mvn clean deploy : pas de server cenral maven 

**mvn clean install** comme expliqué ci-dessus, pour cahque dev repo, et rien d'autre

évenuellement, ce job faire une orb, en tout cas uen factorisatsation : pour que si on cahnge les commandes smaven on ne le change qu'une fois dans la facto, pas 60 fois dans chacun des 60 repos

**Comment by Jean-Baptiste-Lasselle** [comment]
1/2 jours

**Comment by Jean-Baptiste-Lasselle** [comment]
The real dry run test has been successfully tested, while we successfully tested https://github.com/gravitee-io/release/issues/145 : 
* The https://github.com/gravitee-io/gravitee-circleci-orb/releases/tag/1.0.0 release , with [published orb](https://circleci.com/developer/orbs/orb/gravitee-io/gravitee) `gravitee-io/gravitee:1.0.0` contains the definition of a `release` Job
* and when we tested this Orb-factorized `release` Job, we successfully conducted an APIM dry run without dependencies, but on the test Github Organization https://github.com/gravitee-lab 

Neverthe less, to be completely successful, we needed to carry out a test, with an additional automation : 
* the automated deployment of the Circle CI Pipeline defintion `.circleci/config.yml` to all _"Gravitee.io dev repositories"_ 

Therefore, to complete this task, all we have to do is : 
* to test again the Circle CI Orb `gravitee-io/gravitee:1.0.0`
* after we have executed the automated deployment of the Circle CI Pipeline defintion `.circleci/config.yml` to all _"Gravitee.io dev repositories"_ 

Never the less, to do carry out that test, in an isolated, environment (a test Github Org),  rigourously reproducing the production environment (the actual https://github.com/gravitee-io organization), would require, to fork all  _"Gravitee.io dev repositories"_ , and the https://github.com/gravitee-io/release repo.

So, I think 2 tests have to be carried out : 
* first, on the https://github.com/gravitee-lab test environment, knowing that the forked   _"Gravitee.io dev repositories"_ there, are a bit "old" (not reflecting the exact state of their https://github.com/gravitee-io brothers) :  so some maven release might fail there. Just normal.
* Then, on the https://github.com/gravitee-io :  to confirm it all, and with the security, that we know the whole operation is idempotent (won't hurt to run it twice in a row, to add corrections)
