### ISSUE TITLE
Gravitee.io Bundles

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/release#18]
We have to provide complete bundles of Gravitee.io components :

- Gateway with a default repository (MongoDB) + policies + reporters + services
- Management API with a default repository (MongoDB) + policies + reporters + services
- Management WebUI

These bundles must be available as zip or tar.gz archives.

**Comment by NicolasGeraud** [comment]
Maybe we could provide bundles for each repository that are fully supported (I think of the couchbase repository)

**Comment by brasseld** [comment]
@NicolasGeraud: it's a good idea but before we have to move repositories as plugins for main components (gateway, management-api). Currently, these repositories are just traditional jars available in the lib directory (and respective 3rd parties in lib/ext). We have to change this and accept them as plugins. By doing so, a simple paste in the plugins directory would be sufficient to take care of repository implementations.

**Comment by NicolasGeraud** [comment]
see #jenkins-scripts/7
