### ISSUE TITLE
Documentation - Sync with GitHub

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/release#19]
Currently, we are writing documentation using asciidoc in a dedicated repository #gravitee-docs

The goal of this issue is to provide a script which is able to aggregate each readme.adoc from GitHub repositories and create a complete documentation page (in HTML or PDF format) accessible from the gravitee.io website

**Comment by NicolasGeraud** [comment]
we have to fix an issue in the asccidoctor maven plugin
https://github.com/asciidoctor/asciidoctor-maven-plugin/issues/153

**Comment by NicolasGeraud** [comment]
related : #https://github.com/gravitee-io/gravitee-docs/issues/2
