### ISSUE TITLE
Policy configuration : automatic templating for all configuration fields 

### ISSUE THREAD

**Issue by brasseld** [gravitee-io/release#54]
Do Gravitee.io have to provide an automatic templating execution for all fields from a policy configuration ? For example, if we take the transform-queryparameters : actually, input values are not transformed using the template engine. But do we have to provide such functionality ?

How to handle this ? By using an annotation ?

**Comment by NicolasGeraud** [comment]
We have to quantify the overhead of executing templating on each field.

I think it's not to the policy to define if a configuration field can use template or not.

**Comment by brasseld** [comment]
So, you mean that it should be a user's (API publisher) choice ?

**Comment by graviteeio** [comment]
Yes, I think api publisher should choose how to fill policy configuration.

**Comment by NicolasGeraud** [comment]
Yes, I think api publisher should choose how to fill policy configuration.

**Comment by brasseld** [comment]
Does this mean that for each input, we also have to provide a checkbox to know if the policy accept or not the "dynamic configuration" ?
Or the API publisher accept it at the policy level only ?

**Comment by NicolasGeraud** [comment]
you misunderstand me, imho, if performances are not much degraded, it could be transparent and the user does nothing.

Enable templating at policy level could be a trade-off between simplicity and performance

**Comment by brasseld** [comment]
This issue was moved to gravitee-io/ichiou#73
