### ISSUE TITLE
API creation : gateway context path duplication control

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/release#58]
Hello,

I created two API giving them the same context path (in order to see if there was a check).
_My aim here is to prevent issues on duplicated context path, which may happen in case of a high number API creation._
_FYI, i am using the gravitee-docker (demo environment)._

So in my case : 
 - myFirstApi with as context path /demo
 - mySecondApi with as context path /demo

I was expecting an error like "Context path already in use".

At this step, we may have two API with the same context path, but maybe only one really deployed/started, so i deployed & started both APIs, still no error displayed.

When i call the api (http://localhost:8000/demo?api-key=myKey), i'm redirected to "myFirstApi" backend.
If i stop "myFirstApi" and let the "mySecondApi" started, i have as result "No context-path matches the request URI."

So for me that means we can not have two APIs with the same context path, and only the first arrived is taken into account. So there's no checks done on the creation/deploy/starting process.

Could you manage it?
Regards,
Alexandre.

**Comment by aelamrani** [comment]
Hello Alexandre,

This is a known issue => https://github.com/gravitee-io/gravitee-management-rest-api/issues/22

We are working on it...

Thanks for your feedback

**Comment by brasseld** [comment]
Closed by https://github.com/gravitee-io/gravitee-management-rest-api/issues/22
