### ISSUE TITLE
Tag API is not saved

### ISSUE THREAD

**Issue by lusoalex** [gravitee-io/release#60]
Hello,

When i enter some tags on my API, even after saving, it's not taken into account.
When i come back to the API Settings, there's no tag.

Regards,
Alexandre.

**Comment by aelamrani** [comment]
Hello Alexandre,

I can't reproduce it. The saving problem occurs only on tags ? You get a success message after saving ? Are you using the bundle 0.13 ?

BR,
Azize

**Comment by aelamrani** [comment]
Also, do you press <enter key> after writing the tag ?

**Comment by lusoalex** [comment]
I'll check the release number tomorrow in the end of the day,  i make a demo tomorrow and i do not want to brake the settings. 😉

**Comment by lusoalex** [comment]
Hello,
Finally the problem, it was well "press enter" problem.
Also, now tags is well saved, but not taken into account inside the "Search APIs...", is it normal?

**Comment by NicolasGeraud** [comment]
Hello, as you can see here https://github.com/gravitee-io/gravitee-management-webui/blob/master/src/app/api/apisTableMode.html#L40 we use a simple angular filter.

Tags are not mapped on the api list. You could create an issue (or make a PR :) ) to add tags in the json returned by the management api

**Comment by brasseld** [comment]
This issue was moved to gravitee-io/ichiou#77
